package net.epicgamerjamer.mod.againsttoxicity.config;


public class Config {
    private String[] AntiSlurList = {
            ", I understand you're upset, but using slurs no way to talk to others!",
            ", please don't use such offensive language!",
            ", that's not a nice word!",
            ", please find less harmful ways to express your emotions!",
            ", remember that racism and fascism go hand in hand.",
            ", be careful of who you hate, it could be someone you love.",
            ", let's keep the conversation respectful and friendly.",
            ", we can communicate without resorting to hurtful words.",
            ", using slurs isn't helpful or productive in any conversation.",
            ", we should aim for a positive and inclusive environment.",
            ", everyone deserves respect, regardless of our differences.",
            ", slurs are hurtful and have no place in a supportive community.",
            ", spread positivity and make the server a better place."
    };

    private String[] AntiToxicList = {
            ", why so toxic?",
            ", behave yourself!",
            ", did you wake up on the wrong side of the bed?",
            ", try being nice!",
            ", please don't be so mean!",
            ", that's very hurtful!",
            ", did you think before saying that?",
            ", please be respectful of your fellow Minecraft players.",
            ", think of how your words can affect others.",
            ", kindness goes a long way!",
            ", let's keep the conversation positive and uplifting.",
            ", your words can make a difference - choose them wisely.",
            ", spreading positivity makes the community better for everyone.",
            ", be the reason someone smiles today.",
            ", choose kindness, it's a language everyone understands.",
            ", let's create a culture of respect and support.",
            ", uplift others with your words, not bring them down.",
            ", a positive community is built on respectful communication.",
            ", let's resolve conflicts with words, not insults.",
            ", the chat reflects the community - let's make it a great one.",
            ", treat others the way you want to be treated.",
            ", words have power, let's use them to build friendships.",
            ", if you're angry, try taking a break from the game!",
            ", the CPvP community is toxic, but with your help we can make it a better place!",
            ", how would you feel if someone said that to you?",
            ", that was rude.",
            ", that was insensitive.",
            ", I know it's hard, but try to be nice!",
            ", that's no way to talk to others!",
            ", words have power, so let's use them for kindness and understanding.",
            ", let's build bridges with our words, not walls.",
            ", the community thrives when we uplift each other.",
            ", choose empathy and respect in your language.",
            ", a few words can impact many hearts, let's make it positive.",
            ", our words shape the world we live in, make it a better one.",
            ", a respectful chat creates a welcoming environment for all."
    };

    private String[] SlurList = {
            "killall",
            "muncher",
            "munchers",
            "nigg",
            "negro",
            "niga",
            "n1g",
            "tard",
            "fag",
            "f@g",
            "tranny",
            "tr@nny",
            "tranni",
            "trany",
            "niger",
            "niqq",
            "nibb",
            "gypsy",
            "chink",
            "beaner",
            "jew",
            "mentalillness",
            "autis",
            "autism",
            "autistic",
            "blacky",
            "blackie",
            "fucktrans",
            "nijj"
    };

    private String[] ToxicList = {
            "hush",
            "ky$",
            "kiddo",
            "stupid",
            "touch grass",
            "go outside",
            "unloved",
            "ugly",
            "slut",
            "moron",
            "no name",
            "noname",
            "fat",
            "cunt",
            "lucky",
            "luck",
            "fuck up",
            "abuse",
            "abuser",
            "abusing",
            "aids",
            "all shit",
            "annoying",
            "ass",
            "awful",
            "ur bad",
            "your bad",
            "you're bad",
            "youre bad",
            "beta",
            "bitch",
            "bitchass",
            "blud has",
            "boosted",
            "bro only",
            "buddy",
            "bitch",
            "cuck",
            "camper",
            "camping",
            "camp",
            "clapped",
            "clipped",
            "cope",
            "cry",
            "dick",
            "digger",
            "dodge",
            "dodger",
            "dodging",
            "dox",
            "doxx",
            "doxxed",
            "dog shit",
            "dogshit",
            "dumb",
            "dumbass",
            "dummy",
            "easy",
            "end your life",
            "ez",
            "ezz",
            "ezzz",
            "ezzzz",
            "ezzzzz",
            "ezzzzzz",
            "ezpz",
            "fatass",
            "filthy",
            "free",
            "fuck off",
            "fuck u",
            "fuck you",
            "fucker",
            "fucking",
            "fuck off",
            "garbage",
            "gay",
            "get better",
            "get good",
            "ggez",
            "hoe",
            "hop off",
            "horrible",
            "horrid",
            "idiot",
            "i hate",
            "kid",
            "kill ur self",
            "kill urself",
            "kill your self",
            "kill yourself",
            "kys",
            "loser",
            "low iq",
            "monkey",
            "need to die",
            "newgen",
            "nn",
            "nobody asked",
            "nobody cares",
            "nobody likes",
            "no one asked",
            "no one cares",
            "no one likes",
            "not good",
            "noob",
            "npc",
            "own",
            "owned",
            "owning",
            "piss off",
            "pipe down",
            "prac main",
            "pussy",
            "pusy",
            "queer",
            "rando",
            "rape",
            "rider",
            "riding",
            "roll u",
            "roll you",
            "rolled",
            "run",
            "running",
            "runner",
            "scared",
            "shit can",
            "shit on",
            "shitter",
            "shut the",
            "shut up",
            "skill issue",
            "smd",
            "stfu",
            "shut the",
            "shut up",
            "is shit",
            "so shit",
            "so weird",
            "suck",
            "sweat",
            "swat",
            "swatted",
            "swatting",
            "terrible",
            "trash",
            "twat",
            "ur dog",
            "ur shit",
            "weirdo",
            "wild",
            "wise",
            "who are u",
            "who are you",
            "who r u",
            "who r you",
            "worst",
            "you only",
            "your shit"


    };

    private String[] friends = {
            "epicgamerjamer",
            "Server]",
            "Broadcast]",
            "you",
            "me",
            "You",
            "Me",
    };

    private String[] servers = {
            "mcpvp.club"
    };

    private String[] ignore = {
            "was blown up by",
            "was killed by",
            "was slain by",
            "whilst trying to escape",
            "loaded a kit"
    };
    public String[] getAntiSlurList() {
        return AntiSlurList;
    }
    public String[] getAntiToxicList() {
        return AntiToxicList;
    }
    public String[] getSlurList() {
        return SlurList;
    }
    public String[] getToxicList() {
        return ToxicList;
    }
    public String[] getFriends() {
        return friends;
    }
    public String[] getServers() {
        return servers;
    }
    public String[] getIgnore() {return ignore;}
}