package net.epicgamerjamer.mod.againsttoxicity.client;

import net.minecraft.client.MinecraftClient;
// Thanks to Crosby/RacoonDog for making Lists static
public class Lists {
    public static final String[] AntiSlurList = {
            ", be careful of who you hate, it could be someone you love.",
            ", everyone deserves respect, regardless of our differences.",
            ", hurtful slurs have no place in a respectful dialogue.",
            ", I understand you're upset, but using slurs no way to talk to others!",
            ", inclusive discussions require us to refrain from using slurs.",
            ", it's crucial to understand that slurs have no role in civil discourse.",
            ", let's maintain a civil conversation by avoiding offensive slurs.",
            ", please don't use such offensive language!",
            ", please find less harmful ways to express your emotions!",
            ", promoting a respectful environment means avoiding the use of slurs.",
            ", remember that our words can shape our world, so let's choose wisely and reject slurs.",
            ", remember that racism and fascism go hand in hand.",
            ", respecting one another means refraining from hurtful slurs.",
            ", slurs are hurtful and have no place in a supportive community.",
            ", slurs only serve to divide us; let's aim for unity through respect.",
            ", using slurs is never an acceptable way to communicate.",
            ", using slurs isn't helpful or productive in any conversation.",
            ", we should aim for a positive and inclusive environment.",
            ", we should all strive to communicate without resorting to slurs.",
    };

    public static final String[] AntiToxicList = {
            ", a foundation of our community is built on respectful communication.",
            ", a positive community thrives on respectful communication.",
            ", choose to uplift others with your words, rather than bring them down.",
            ", consider how you'd like to be treated and extend that to others.",
            ", consider taking a break from the game if you're feeling angry.",
            ", consider the impact of your words; they hold weight.",
            ", don't be rude!",
            ", even a few words can have a significant impact on many hearts; let's make them positive.",
            ", harness the power of words to build friendships.",
            ", hurtful comments are not welcome here.",
            ", it can be difficult, but let's make an effort to be nice.",
            ", it's not acceptable to be mean.",
            ", let's aim for communication without resorting to hurtful words.",
            ", let's encourage a culture of respect and support.",
            ", let's encourage kindness from everyone.",
            ", let's ensure the conversation remains respectful and friendly.",
            ", let's foster a positive and uplifting conversation.",
            ", let's maintain a respectful chat to create a welcoming environment for all.",
            ", let's resolve conflicts through constructive words, not insults.",
            ", let's use words to build bridges, not walls.",
            ", let's work together to make the chat a place of positivity.",
            ", let's work together to spread positivity and improve the community.",
            ", our community values respectful communication; let's uphold that.",
            ", remember that your words can have a positive impact on many hearts.",
            ", remember, your words possess the power to promote kindness and understanding.",
            ", remember, your words shape the world we live in; let's make it a better place.",
            ", strive to use empathy and respect in your language.",
            ", take a moment to think before speaking.",
            ", treat others as you would like to be treated.",
            ", while the CPvP community can be toxic, we can work together to make it better.",
            ", why so toxic?",
    };

    public static final String[] SlurList = {
            "autis",
            "beaner",
            "blackie",
            "blacky",
            "burnall",
            "burnthe",
            "chink",
            "currymuncher",
            "fag",
            "faqq",
            "fucklgbt",
            "fucktrans",
            "gasall",
            "gasthe",
            "gypsy",
            "jew",
            "killall",
            "killthe",
            "mentalillness",
            "n1g",
            "negro",
            "negg",
            "ngger",
            "nibb",
            "niga",
            "niger",
            "nigg",
            "nijj",
            "niqq",
            "nlgg",
            "tard",
            "trann",
            "trany",
    };

    public static final String[] ToxicList = {
            "abuse",
            "abuser",
            "abusing",
            "aids",
            "annoying",
            "ass",
            "asss",
            "assss",
            "asssss",
            "assssss",
            "asssssss",
            "asshole",
            "awful",
            "beta",
            "bitch",
            "bitchass",
            "boosted",
            "buddy",
            "camp",
            "camper",
            "camping",
            "clapped",
            "clipped",
            "cope",
            "cry",
            "cuck",
            "cunt",
            "dick",
            "digger",
            "dodge",
            "dodger",
            "dodging",
            "dogshit",
            "dox",
            "doxx",
            "doxxed",
            "dumb",
            "dumbass",
            "dummy",
            "easy",
            "ez",
            "ezpz",
            "ezz",
            "ezzz",
            "faceplacer",
            "fan",
            "fanning",
            "fat",
            "fatass",
            "fatherless",
            "fatty",
            "filthy",
            "fucker",
            "fuckface",
            "fucking",
            "garbage",
            "gay",
            "ggez",
            "glaze",
            "glazing",
            "groomer",
            "hoe",
            "horrible",
            "horrid",
            "hush",
            "idiot",
            "kid",
            "kiddo",
            "kids",
            "kiddos",
            "kys",
            "l",
            "lagger",
            "ll",
            "lll",
            "llll",
            "lllll",
            "loser",
            "luck",
            "lucky",
            "mf",
            "monkey",
            "montage",
            "moron",
            "motherfucker",
            "newgen",
            "ngga",
            "nn",
            "noname",
            "noob",
            "noobs",
            "npc",
            "obese",
            "obesity",
            "own",
            "owned",
            "owning",
            "pedo",
            "pinger",
            "preplacer",
            "puss",
            "pussy",
            "pusy",
            "qd",
            "queer",
            "quickdrop",
            "rider",
            "riding",
            "rolled",
            "runner",
            "running",
            "shut",
            "slit",
            "slut",
            "smd",
            "spammer",
            "spamming",
            "sped",
            "sucks",
            "swat",
            "swatted",
            "swatting",
            "sweat",
            "tage",
            "terrible",
            "trash",
            "twat",
            "ugly",
            "unloved",
            "weirdo",
            "wierdo",
            "wise",
            "random",
            "rape",
            "raping",
            "scared",
            "shitbox",
            "shitcan",
            "shitter",
            "stfu",
            "sthu",
            "stupid"
    };
    public static final String[] ToxicList2 = {
            "all shit",
            "be quiet",
            "blud cant",
            "blud has",
            "blud only",
            "bro cant",
            "bro has",
            "bro only",
            "dog shit",
            "end it",
            "end ur",
            "ezez",
            "ezzzz",
            "face placer",
            "fuck the",
            "fuck off",
            "fuck u",
            "get a life",
            "get better",
            "get good",
            "go back to",
            "go outside",
            "hang ur",
            "hop off",
            "i hate",
            "is crazy",
            "is shit",
            "is wild",
            "just bad",
            "just suck",
            "keep talking",
            "kill ur",
            "k ys",
            "k y s",
            "ky s",
            "llllll",
            "lil bro",
            "low iq",
            "need to die",
            "nns",
            "no life",
            "no name",
            "no one asked",
            "no one cares",
            "no one likes",
            "nobody asked",
            "nobody cares",
            "nobody likes",
            "not good",
            "pipe down",
            "piss off",
            "prac main",
            "pre placer",
            "quick drop",
            "really bad",
            "roll u",
            "shit box",
            "shit can",
            "shit on",
            "shut the",
            "shut u",
            "skill issue",
            "so bad",
            "so free",
            "so shit",
            "so weird",
            "so wierd",
            "still los",
            "touch grass",
            "u bad",
            "u dog",
            "u only",
            "u shit",
            "u suck",
            "ur bad",
            "ur dog",
            "ur shit",
            "who r",
            "who tf",
            "u only",
    };

    public static final String[] IgnoreNames = {
            "server",
            "broadcast",
            "shout",
            "soapbar",
            "you",
            "me",
            "--",
            MinecraftClient.getInstance().player.getName().getString()
    };
}